PORT: 5000
LLM_TYPE: "claude 3.5 sonnet"
COTOMI_API_KEY: "your_cotomi_api_key"
COTOMI_BASE_URL: "your_cotomi_base_url"
AZURE_API_KEY: "your_azure_api_key"
AZURE_ENDPOINT: "your_azure_endpoint"
AZURE_API_VERSION: "your_azure_api_version"
LINE_CHANNEL_ACCESS_TOKEN: "your_line_channel_access_token"
LINE_CHANNEL_SECRET: "your_line_channel_secret"
HOT_PEPPER_API_KEY: "your_hot_pepper_api_key"
HOT_PEPPER_LAT: "35.71448464596413"
HOT_PEPPER_LNG: "139.76178782969163"
HOT_PEPPER_RANGE: "3"
AWS_ACCESS_KEY_ID: "your_aws_access_key_id"
AWS_SECRET_ACCESS_KEY: "your_aws_secret_access_key"
AWS_REGION: "your_aws_region"
MYSQL_HOST: "localhost"
MYSQL_USER: "easylunch_user"
MYSQL_PASSWORD: "same as your mysql password in src/db/docker/.env_mysql" 
GOOGLE_PLACES_API_KEY: "your_google_places_api_key"
MYSQL_DATABASE: "easylunch_database"
IS_GOOGLE_CLOUD: "False"

