PORT: 5000
COTOMI_API_KEY: "your_cotomi_api_key"
COTOMI_BASE_URL: "your_cotomi_base_url"
AZURE_API_KEY: "your_azure_api_key"
LINE_CHANNEL_ACCESS_TOKEN: "your_line_channel_access_token"
LINE_CHANNEL_SECRET: "your_line_channel_secret"
HOT_PEPPER_API_KEY: "your_hot_pepper_api_key"
AWS_ACCESS_KEY_ID: "your_aws_access_key_id"
AWS_SECRET_ACCESS_KEY: "your_aws_secret_access_key"
AWS_REGION: "your_aws_region"
